[dependencies.llvm-nhb]
path = "llvm-nhb"

[package]
name = "bcz_programming_language"
version = "0.3.0"
edition = "2021"

[dependencies]
strum = "0.26.3"
strum_macros = "0.26.4"
auto-const-array = "0.2.1"